import math
"""Configuration constants for SLAM simulation"""

# World settings
WORLD_WIDTH = 1200
WORLD_HEIGHT = 700
MAP_RESOLUTION = 0.05  # meters per pixel
FPS = 60

# Robot settings
ROBOT_RADIUS = 0.3  # meters
MAX_VELOCITY = 1.0  # m/s
MAX_ANGULAR_VELOCITY = 1.0  # rad/s

# Lidar settings
LIDAR_BEAMS = 360
LIDAR_RANGE = 10.0  # meters
LIDAR_FOV = 2* math.pi
LIDAR_NOISE_STD = 0.1

# Odometry noise
ODOM_NOISE_TRANSLATION = 0.1
ODOM_NOISE_ROTATION = 0.05

# SLAM settings
LANDMARK_DETECTION_THRESHOLD = 0.5
DATA_ASSOCIATION_THRESHOLD = 1.0

# Visualization
BACKGROUND_COLOR = (255, 255, 255)
OBSTACLE_COLOR = (0, 0, 0)
ROBOT_COLOR = (0, 0, 255)
ESTIMATED_ROBOT_COLOR = (255, 0, 0)
LANDMARK_COLOR = (0, 255, 0)
ESTIMATED_LANDMARK_COLOR = (255, 165, 0)
